spring.application.name=Kaoyan

# ?????
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/kaoyan_forum?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8

# MyBatis-Plus ??
mybatis-plus.mapper-locations=classpath:mapper/**/*.xml
mybatis-plus.configuration.map-underscore-to-camel-case=true

# ????
logging.level.com.zzu.kaoyan.mapper=debug