spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kaoyan_forum?useSSL=false&serverTimezone=Asia/Shanghai # 建议用上海时区
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# 必须改为 mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # 修正为你实际的实体类所在包，如果分模块了，可以用通配符比如 com.zzu.kaoyan.**.entity
  type-aliases-package: com.zzu.kaoyan.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl